LocalPlayer.state:set('disableTasks', false, true)

AddStateBagChangeHandler('disableTasks', nil, function(bagName, key, value) 
    local entity = GetPlayerFromStateBagName(bagName)
    if (entity == 0) or (PlayerId() ~= entity) or (not Citizen) then return; end;

    Citizen.CreateThread(function()
        while (LocalPlayer.state.disableTasks) do
            BlockWeaponWheelThisFrame()
            DisableControlAction(0, 29, true)
            DisableControlAction(0, 22, true)
            DisableControlAction(0, 47, true)
            DisableControlAction(0, 56, true)
            DisableControlAction(0, 57, true)
            DisableControlAction(0, 73, true)
            DisableControlAction(0, 137, true)
            DisableControlAction(0, 166, true)
            DisableControlAction(0, 167, true)
            DisableControlAction(0, 169, true)
            DisableControlAction(0, 170, true)
            DisableControlAction(0, 182, true)
            DisableControlAction(0, 187, true)
            DisableControlAction(0, 188, true)
            DisableControlAction(0, 189, true)
            DisableControlAction(0, 190, true)
            DisableControlAction(0, 243, true)
            DisableControlAction(0, 245, true)
            DisableControlAction(0, 257, true)
            DisableControlAction(0, 288, true)
            DisableControlAction(0, 289, true)
            DisableControlAction(0, 311, true)
            DisableControlAction(0, 344, true)		
            DisablePlayerFiring(PlayerPedId(), true)
            Citizen.Wait(1)
        end
    end)
end)